# we don't actually want to test here, but Travis can't just release things..
language: node_js
node_js:
    - 6

deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  api_key:
    secure: icV2SA7IdQPtexla2+MNOl4/Za5ZwGIdxH/KlRuiMAUUGIWFslbwr6PEHuETziT0fEreGCgyE7Rjs5sELOy276GsTDAU6zXjZYNxmtxVPpHMHTie2J4OOCrqT0btAidbEKw/oIbFkU6nX0ROQ6PObRIEW3ezQaUXca5GAaXKKpbM1QEBqnYd/F9kGvNonfU6j2jbzpqt26rocAQIqyvmJHtS6pHaGZqNfWw5xmrECw5Wn4+yiT3pGCDX74VZbep+5Tf09rcs/xo1mN9eEBsUhXTV+1vML5Sf7fKG5HCZbETfGnhLNwPyW3Cm1+t9YEZBrc95Oh3Y4lBiYY3bsn/Dbh05wVBmSZLzsRSzGImxTgXHVqqz90vBwDsd/Rm2vkxd8rkQissmB9c1kHlPL0h63k4ITex7HuRDd+rQzpU3GRDZ/IzbqpsDFgSugU8pJphusMiQvUC8rtTeIMmpJS7oNoOsfHaIY+6JGix44wutTBxl/oT2G2aYCccxC01n75JyLWSBuVOR3bFYs6T1UX0CycMuoITtQDKdUK3+fxSALlo3jj8DbRh9G3TeviF5LM1jA7Msaem77H1pqijKGqGzlIWAx1f6SspRlRm9HR5bBQtYwo0oqpfm1740UjSnF1gukgOOt1Yz/0XkXFbC4SydfWehYiVh+4MRyYDy6x99OnU=
  on:
    tags: true
    repo: taskcluster/json-e
