# we don't actually want to test here, but Travis can't just release things..
language: node_js
node_js:
    - 6

deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  api_key:
    secure: AKXLwYXa2L+KdxsDFNHI4kJ1Y1G5FJA/sKBG4vdSYyM5GUuhsAc6gHh7UhKv4YkucGqxR/UxzIxkTDHUV2Rdivw0D2uChSJ2o7zb+z4iaKJZvjg7uCVu5xkT+mViMgIieIvDBcg50es7W3YZXL4QIBUHjh8+Y5SMtMSG5AryqOXzPOLRbeJA1nCnBJ+VNUuiFWA0yQg0apAJ5zptPTkaNfpXE7zSOY3EaoYZ/0qadHszoRL72g8Bb2lXLxheIYhj1rDzDAFSQ1tZfBGUy023a6ST3iA5Qn867IF19A5rPlJrlTycNY1/ZIw/vK84rD+oOrh0qDGnQxaNU/R1X9Q9W5MWuIdM+yEuCX+zYCV5FVDH4/KCTLOKgmfIBEM996uxooZ260C8KSc/iHYFHRYgirwrUcr4E+wr2T8C0SF/bRN2Wie9LxVnwH9u/vzxnyFhHEZMxsNkiZ+wM0/uLKSSiJhGCzKi52e7RDgV9kr2I3jPnR1ZRSVk3xISG8yDxjj1AHTq4q39tMS2JGvf7yE0+wOyjux728+NWHJuN2oH/gFoKNJ+ss8oppVChunIvJYu4B9XHW5IMW9JV1X8nKSHROKJawqg7VeCFVq2LFy/u436euwwBTsqyCim5okvCn/4qmIE2LZ3lYyxOPWX2m7hXud+HtGWGxlg36wudNB1yJ0=
  on:
    tags: true
    repo: taskcluster/json-e
