language: node_js
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  api_key:
    secure: Wr0mpOUQw1E6KSCdRAHTImMsqp9tGpIRVSugvEjOZPK0mUdP0hokcWGgC2hZyCAtpAsZ+SJtwGdad41zRP7C3NtuOKXmC4GGEQB4PoGA73ijScMi+rr3azgedzBpd8bbTAsmYE6yk+kjSuSz3C4JpEi3ZYqscioKrvmNRdKIyR/1zL7M9VWRymQa1Ct3B627CiX9o+1XPQex2llAN9E6bhkQYX9fYry18sk4thN6B8qsG1NpA1ri+HuKKlNAGvYDAP1qiYIBLwSFbisBJwsOEedtNEQQ2uihR88yK2wltEexRTWC+giSrggqEOhcjRU3T8kB6fZt+XN7NDRIIKKNurZXtdT8znZpAWs+kVVmdNmAkSUlAwe6HQExIPbfsGyRf8EveW5ltMWrGhLUdbAYqDT+0E3do4VnNvQwSLaJd2ogGWiAEj5/wwD1maljUJ6fybJNDR4UuVBN5F9zcnunH+G3lTdq4Em0kiKxpzytH0cWN/EkkwfdRl8j7JsJ6f21HTCl6GbR3egCkgnb6OC7y8qtmFQz8KQZNXVpJyS7EGDYCZlLaKiZV4bIONg4sLfywNJXgvIbA9cVFdkrzcn5L/Sfm89D72dExAtCLk6iVGE4T/rNF4OjwvOXtwtGbIk2ZbohYzw8SDq0PK3yl23VYh0jU4WKmyDs81uZ8VlS34Y=
  on:
    tags: true
    repo: taskcluster/json-e
